---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter-notebook
spec:
  # The LoadBalancer type is required to get a public IP
  # address when running on Google Container Engine.
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  selector:
    name: deforestprob
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deforestprob
  labels:
    name: deforestprob
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: deforestprob
    spec:       
      containers:
        - name: debian-deforestprob
          image: ghislainv/docker-deforestprob
          ports:
            - name: http
              containerPort: 8888
