apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  ports:
  - protocol: TCP
    name: http
    port: 8888
    targetPort: 8888
  selector:
    run: deforestprob-dep
  type: LoadBalancer
